### ISSUE TITLE
docker-credential-desktop.exe not installed or not available in PATH

### ISSUE THREAD

**Issue by samuel-fonseca** [imarc/ops#23]
### Windows info

```
Edition	Windows 10 Home
Version	20H2
Installed on	‎9/‎1/‎2020
OS build	19042.630
Experience	Windows Feature Experience Pack 120.2212.31.0
```

### Debian 

```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Docker info

```
Docker version 19.03.13, build 4484c46d9d
```

## Issue

OPS installs ok locally on the WSL machine. However, I am running into issues when attempting to start OPS locally.

I keep running into the following error:

```console
samfonseca@xps13:~/Sites$ ops start
Starting ops services...

Pulling dnsmasq (jpillora/dnsmasq:1.1.0)...
Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 1070, in up
  File "compose/cli/main.py", line 1066, in up
  File "compose/project.py", line 615, in up
  File "compose/service.py", line 356, in ensure_image_exists
  File "compose/service.py", line 1267, in pull
  File "compose/progress_stream.py", line 99, in get_digest_from_pull
  File "compose/service.py", line 1234, in _do_pull
  File "docker/api/image.py", line 396, in pull
  File "docker/auth.py", line 48, in get_config_header
  File "docker/auth.py", line 324, in resolve_authconfig
  File "docker/auth.py", line 235, in resolve_authconfig
  File "docker/auth.py", line 262, in _resolve_authconfig_credstore
  File "docker/auth.py", line 287, in _get_store_instance
  File "docker/credentials/store.py", line 25, in __init__
docker.credentials.errors.InitializationError: docker-credential-desktop.exe not installed or not available in PATH
[13120] Failed to execute script docker-compose
```

**Comment by samuel-fonseca** [comment]
[This answer on docker's forum](https://forums.docker.com/t/docker-credential-desktop-exe-executable-file-not-found-in-path-using-wsl2/100225/5) helped me bypass the problem.

I updated `credsStore` to `credStore` in the `~/.docker/config.json` file.

```json
{
  "credStore": "desktop.exe"
}
```

Not sure what exactly is causing it. This is a fresh Debian install using WSL 2 by default.
